model:
  arch: "UNet" # DeepLabX, DeepLab, UNetResnet, UNet
  out_layer_size: 512
  in_channels: 3
  backbone: "resnet50" # resnet18, resnet34, resnet50, resnet101
  output_stride: 16
  freeze_bn: False
  freeze_backbone: False
  use_smp: True # if this is true, https://github.com/qubvel/segmentation_models.pytorch is used
  # for defining and loading the models instead of parameters above
  smp:
    arch: "FPN"
    backbone: "timm-regnetx_016"
    pretrained_weights: "imagenet"
    out_layer_size: 512
    in_channels: 3
    version: "1"

  version: "1"

data:
  folder_structure: "separate_json" # separate, separate_json, unified
  dataset: "coco"
  input_size: 224
  nb_classes: 81

  crop_image:
      status: 0
      x_min: 0
      y_min: 0
      x_max: 0
      y_max: 0
      
  augmentations:
  
    ShiftScaleRotate:
      shift_limit: 0.2
      scale_limit: 0.2
      rotate_limit: 180
      probability: 0.5

    RGBShift:
      r_shift_limit: 50
      g_shift_limit: 50
      b_shift_limit: 50
      probability: 0.3

    RandomBrightnessContrast:
      brightness_limit: 0.2
      contrast_limit: 0.3
      probability: 0.3

training:
  optimizer: "Lion"
  load_opt: True
  criterion: 'ProxyAnchor' # CrossEntropyLoss2d | DiceLoss | FocalLoss | CrossEntropyDiceLoss | BinaryCrossEntropyWithLogits2d
  epochs: 200
  batch_size: 8
  learning_rate: 0.00001
  device: "cuda"
  num_workers: 4

proxy_anchor:
  alpha: 32
  margin: 0.8
  lr: 0.01
  steps: 500

inference:
  device: "cuda"
  num_of_neighbors: 1
  threshold: 0.0

#-- Guidance for models' configuration --#
#  model = UNet(
#      num_classes=cfg.model.num_classes,
#      in_channels=3,
#      freeze_bn=cfg.model.freeze_bn
#  )

#  model = UNetResnet(
#      num_classes=cfg.model.num_classes,
#      in_channels=3,
#      backbone=cfg.model.backbone,
#      pretrained=True,
#      freeze_bn=cfg.model.freeze_bn,
#      freeze_backbone=cfg.model.freeze_backbone
#  )

#  model = DeepLab(
#      num_classes=cfg.model.num_classes,
#      in_channels=3,
#      backbone=cfg.model.backbone,
#      pretrained=True,
#      output_stride=cfg.model.output_stride,
#      freeze_bn=cfg.model.freeze_bn,
#      freeze_backbone=cfg.model.freeze_backbone
#  )

#  model = DeepLabX(
#      num_classes=cfg.model.num_classes,
#      in_channels=3,
#      backbone=cfg.model.backbone,
#      pretrained=True,
#      output_stride=cfg.model.output_stride,
#      freeze_bn=cfg.model.freeze_bn,
#      freeze_backbone=cfg.model.freeze_backbone
#  )


